import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Bird, BookOpenCheck, CheckCircle2, GraduationCap, HeartHandshake, School, Sparkles, UsersRound } from "lucide-react";

const benefits = [
  [GraduationCap, "Prática que continua fora da aula", "Treinos curtos transformam o conteúdo trabalhado pela escola em uma rotina leve e frequente."],
  [BookOpenCheck, "Professor no controle", "A escola define o conteúdo e acompanha os acessos sem transformar o progresso em um ranking punitivo."],
  [BarChart3, "Evolução que pode ser acompanhada", "Participação, treinos e habilidades praticadas formam uma visão objetiva para a coordenação."],
];

export default function SchoolLanding() {
  return <main className="school-landing">
    <header className="school-nav"><Link className="brand" href="/escolas"><span className="brand-mark"><Bird size={24} strokeWidth={3} /></span><span>Bird<span className="brand-dot">League</span></span></Link><nav><a href="#produto">O produto</a><a href="#pedagogia">Pedagogia</a><a href="#mvp">MVP</a><Link className="btn btn-blue btn-small" href="/">Área do aluno</Link></nav></header>
    <section className="school-hero">
      <div><div className="eyebrow">Uma experiência Bluebird</div><h1>Prática de idiomas que o aluno <em>quer continuar.</em></h1><p>BirdLeague transforma cada treino em uma jornada: o aluno aprende, ensina seu Bloo e vê o esforço ganhar vida.</p><div className="hero-actions"><a className="btn btn-primary" href="#mvp">Conhecer o MVP <ArrowRight size={19} /></a><Link className="btn btn-ghost" href="/">Ver jornada do aluno</Link></div><div className="institution-proof"><span><CheckCircle2 /> Gamificação pedagógica</span><span><CheckCircle2 /> Identidade Bluebird</span><span><CheckCircle2 /> Progresso sem punição</span></div></div>
      <div className="school-visual"><div className="school-orbit orbit-one">Ensinar</div><div className="school-orbit orbit-two">Aprender</div><div className="school-orbit orbit-three">Evoluir</div><Image src="/assets/bloo/hatchling-happy.png" width={1024} height={1024} alt="Bloo, companheiro de aprendizagem do BirdLeague" priority /></div>
    </section>
    <section id="produto" className="school-section intro-section"><div className="eyebrow">Mais que um quiz</div><h2>Aprendizado, vínculo e progresso no mesmo ciclo.</h2><p className="section-lead">O Bloo é um companheiro que nasce e evolui conforme o aluno pratica. Cada resposta oferece feedback e torna o próximo objetivo mais claro.</p><div className="benefit-grid">{benefits.map(([Icon, title, text]) => { const C = Icon as typeof GraduationCap; return <article key={title as string}><span><C /></span><h3>{title as string}</h3><p>{text as string}</p></article>; })}</div></section>
    <section id="pedagogia" className="school-section pedagogy-section"><div className="pedagogy-image"><Image src="/assets/bloo/egg-crack-3.png" width={1024} height={1024} alt="Ovo do Bloo prestes a nascer" /></div><div><div className="eyebrow">Como funciona para o aluno</div><h2>Uma jornada curta, clara e emocional.</h2><ol><li><strong>A escola cria o acesso.</strong><span>O estudante recebe login e senha definidos pela equipe.</span></li><li><strong>O conteúdo vira missão.</strong><span>Treinos apresentam perguntas e feedback imediato.</span></li><li><strong>O esforço ganha vida.</strong><span>O ovo racha, o Bloo nasce e novas conquistas mostram a evolução.</span></li></ol></div></section>
    <section className="school-section control-section"><div><div className="eyebrow">Para professores e coordenação</div><h2>O professor continua no controle.</h2><p className="section-lead">O BirdLeague amplia o trabalho pedagógico. A proposta é apoiar decisões, celebrar constância e mostrar quais habilidades precisam de novas oportunidades de prática.</p></div><div className="control-cards"><article><UsersRound /><strong>Acessos administrados</strong><span>Somente estudantes criados pela escola entram na plataforma.</span></article><article><HeartHandshake /><strong>Engajamento saudável</strong><span>Erros geram orientação e novas tentativas, não perda de progresso.</span></article><article><School /><strong>Produto da comunidade</strong><span>Personagem, linguagem e experiência conectados à identidade Bluebird.</span></article></div></section>
    <section id="mvp" className="school-section mvp-section"><div><div className="eyebrow">Escopo atual</div><h2>O primeiro voo do BirdLeague.</h2><p>O MVP valida a entrada segura, o primeiro treino, o nascimento do Bloo e a rotina inicial de aprendizado.</p></div><ul><li><CheckCircle2 /> Administração de acessos de estudantes</li><li><CheckCircle2 /> Login individual e seguro</li><li><CheckCircle2 /> Primeiro treino de Inglês</li><li><CheckCircle2 /> Feedback para cada resposta</li><li><CheckCircle2 /> Nascimento e nome do Bloo</li><li><CheckCircle2 /> Progresso e conquistas iniciais</li></ul></section>
    <section className="school-cta"><Sparkles /><h2>Transforme prática de idioma em uma jornada que o aluno quer continuar.</h2><p>Conheça a experiência atual do BirdLeague e acompanhe a evolução do MVP.</p><Link className="btn btn-primary" href="/">Entrar no BirdLeague <ArrowRight size={19} /></Link></section>
    <footer className="school-footer"><div className="brand"><span className="brand-mark"><Bird size={22} /></span><span>Bird<span className="brand-dot">League</span></span></div><p>Uma experiência gamificada de aprendizagem criada para a Bluebird.</p></footer>
  </main>;
}
