"use client";
import { Bird, BookOpen, Database, Home, KeyRound, Layers3, LogOut, ShieldCheck, UsersRound } from "lucide-react";
import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import { api, AuthUser, request } from "@/lib/api";
import { BankQuestion, errorMessage, levels, Theme, Workspace } from "@/lib/management";
const menu=[["overview",Home,"Início"],["classes",Layers3,"Turmas"],["students",UsersRound,"Alunos"],["admins",ShieldCheck,"Administradores"],["themes",BookOpen,"Temas"],["questions",Database,"Banco de questões"],["password",KeyRound,"Minha senha"]] as const;
type Tab=typeof menu[number][0];
type Editing={kind:"class"|"user"|"reset"|"enroll"|"question"|"theme"|"release";id?:string;admin?:boolean};
const value=(data:FormData,name:string)=>String(data.get(name)??"");
function Input({label,name,initial="",type="text",required=true,minLength,maxLength=120}:{label:string;name:string;initial?:string;type?:string;required?:boolean;minLength?:number;maxLength?:number}){return <label className="field">{label}<input className="input" name={name} defaultValue={initial} type={type} required={required} minLength={minLength} maxLength={maxLength} autoComplete={type==="password"?"new-password":"off"}/></label>;}
function Select({label,name,initial,children}:{label:string;name:string;initial?:string;children:ReactNode}){return <label className="field">{label}<select name={name} defaultValue={initial} className="input">{children}</select></label>;}
function Button({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button type="button" className="btn btn-ghost btn-small" onClick={onClick}>{children}</button>;}
function Editor({title,children,onSave,onClose}:{title:string;children:ReactNode;onSave:(data:FormData)=>Promise<void>;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError("");try{await onSave(data);onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <section className="admin-card editor"><h2>{title}</h2><form onSubmit={submit}><fieldset disabled={busy} className="editor-fields">{children}{error&&<p className="form-error wide" role="alert">{error}</p>}<div className="form-actions"><Button onClick={onClose}>Cancelar</Button><button className="btn btn-blue btn-small" disabled={busy}>{busy?"Salvando…":"Salvar"}</button></div></fieldset></form></section>;
}
export default function AdminApp({token,user,onLogout}:{token:string;user:AuthUser;onLogout:()=>void}){
 const [tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<Workspace|null>(null),[bank,setBank]=useState<BankQuestion[]>([]),[edit,setEdit]=useState<Editing|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(1);
 const refresh=useCallback(async()=>{const [workspace,questions]=await Promise.all([request<Workspace>("/admin/workspace",{},token),request<BankQuestion[]>("/admin/questions",{},token)]);setData(workspace);setBank(questions);},[token]);
 useEffect(()=>{refresh().catch(e=>setError(errorMessage(e)));},[refresh]);
 async function save(path:string,body:unknown,method="POST"){await request(path,{method,body:JSON.stringify(body)},token);await refresh();setNotice("Alteração salva no servidor.");}
 async function action(path:string,body:unknown){setError("");try{await save(path,body);}catch(e){setError(errorMessage(e));}}
 const open=(kind:Editing["kind"],id?:string,admin?:boolean)=>{setEdit({kind,id,admin});setNotice("");};
 const changeTab=(next:Tab)=>{setTab(next);setEdit(null);setSearch("");setPage(1);setNotice("");};
 const filter=<T,>(items:T[],label:(item:T)=>string)=>items.filter(item=>label(item).toLowerCase().includes(search.toLowerCase()));
 const paginate=<T,>(items:T[])=>items.slice((page-1)*10,page*10);
 const pager=(count:number)=><div className="pagination"><span>{count} registro(s) · página {page} de {Math.max(1,Math.ceil(count/10))}</span><Button onClick={()=>setPage(p=>Math.max(1,p-1))}>Anterior</Button><button className="btn btn-ghost btn-small" disabled={page*10>=count} onClick={()=>setPage(p=>p+1)}>Próxima</button></div>;
 const rowUser=data?.users.find(p=>p.id===edit?.id),rowClass=data?.classes.find(c=>c.id===edit?.id),rowTheme=data?.themes.find(t=>t.id===edit?.id),rowQuestion=bank.find(q=>q.id===edit?.id);
 const languageOptions=data?.languages.map(l=><option key={l.id} value={l.id}>{l.name}</option>);
 const groupOptions=data?.classes.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.name} · {c.period}</option>);
 const persons=data?filter(data.users.filter(p=>p.role===(tab==="admins"?"Admin":"Student")),p=>`${p.displayName} ${p.login}`):[];
 const groups=data?filter(data.classes,c=>`${c.name} ${c.period}`):[];
 const themes=data?filter(data.themes,t=>`${t.versions[0]?.title} ${t.code}`):[];
 const questions=filter(bank,q=>`${q.code} ${q.versions[0]?.prompt} ${q.versions[0]?.difficulty}`);
 return <main className="admin"><aside className="sidebar"><div className="brand"><Bird/><span>BirdLeague</span></div><nav className="side-nav">{menu.map(([id,Icon,label])=><button key={id} title={label} aria-label={label} className={`side-link ${tab===id?"active":""}`} onClick={()=>changeTab(id)}><Icon size={19}/><span>{label}</span></button>)}</nav><button className="side-link" onClick={onLogout}><LogOut size={19}/><span>Sair</span></button></aside><section className="admin-content"><header className="admin-head"><div><strong>Bluebird Idiomas</strong><small>Portal administrativo</small></div><span>{user.displayName}</span></header><div className="admin-main"><div className="admin-title"><h1>{menu.find(m=>m[0]===tab)?.[2]}</h1><div className="row-actions">{tab==="classes"&&<Button onClick={()=>open("class")}>Nova turma</Button>}{(tab==="students"||tab==="admins")&&<Button onClick={()=>open("user",undefined,tab==="admins")}>{tab==="admins"?"Novo administrador":"Novo aluno"}</Button>}{tab==="themes"&&<Button onClick={()=>open("theme")}>Novo tema</Button>}{tab==="questions"&&<Button onClick={()=>open("question")}>Nova pergunta</Button>}<Button onClick={()=>refresh().catch(e=>setError(errorMessage(e)))}>Atualizar</Button></div></div>
 {error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="success-message">{notice}</p>}
 {!data?<p>Carregando dados do servidor…</p>:<>
 {edit?.kind==="class"&&<Editor key={edit.id??"new-class"} title={edit.id?"Editar turma":"Nova turma"} onClose={()=>setEdit(null)} onSave={f=>save(`/admin/classes${edit.id?`/${edit.id}`:""}`,{name:value(f,"name"),languageId:value(f,"languageId"),period:value(f,"period"),levelLabel:value(f,"levelLabel"),isActive:f.has("isActive")},edit.id?"PUT":"POST")}><Input label="Nome da turma" name="name" initial={rowClass?.name}/><Select label="Idioma" name="languageId" initial={rowClass?.languageId}>{languageOptions}</Select><Input label="Nível pedagógico (informativo)" name="levelLabel" initial={rowClass?.levelLabel??""} required={false} maxLength={40}/><Input label="Período / horário" name="period" initial={rowClass?.period} maxLength={60}/><label><input type="checkbox" name="isActive" defaultChecked={rowClass?.isActive??true}/> Turma ativa</label></Editor>}
 {edit?.kind==="user"&&<Editor key={edit.id??"new-user"} title={edit.id?"Editar usuário":edit.admin?"Novo administrador":"Novo aluno"} onClose={()=>setEdit(null)} onSave={async f=>{const body={fullName:value(f,"fullName"),login:value(f,"login")};if(edit.id)await save(`/admin/users/${edit.id}`,{...body,isActive:f.has("isActive")},"PUT");else{if(value(f,"password")!==value(f,"confirm"))throw new Error("password_confirmation");await save(`/admin/${edit.admin?"admins":"students"}`,{...body,password:value(f,"password"),...(!edit.admin&&value(f,"classId")?{classId:value(f,"classId")}: {})});}}}><Input label="Nome completo" name="fullName" initial={rowUser?.displayName}/><Input label="Login" name="login" initial={rowUser?.login} minLength={3} maxLength={80}/>{edit.id?<label><input type="checkbox" name="isActive" defaultChecked={rowUser?.isActive}/> Usuário ativo</label>:<><Input label="Senha inicial" name="password" type="password" minLength={edit.admin?12:8} maxLength={128}/><Input label="Confirmar senha" name="confirm" type="password" minLength={edit.admin?12:8} maxLength={128}/>{!edit.admin&&<Select label="Matrícula inicial" name="classId"><option value="">Sem turma — matricular depois</option>{groupOptions}</Select>}</>}</Editor>}
 {edit?.kind==="reset"&&rowUser&&<Editor title={`Redefinir senha de ${rowUser.displayName}`} onClose={()=>setEdit(null)} onSave={async f=>{if(value(f,"password")!==value(f,"confirm"))throw new Error("password_confirmation");await save(`/admin/users/${rowUser.id}/password`,{password:value(f,"password")});}}><Input label="Nova senha provisória" name="password" type="password" minLength={rowUser.role==="Admin"?12:8} maxLength={128}/><Input label="Confirmar nova senha" name="confirm" type="password" maxLength={128}/><p className="wide">O usuário deverá trocar a senha no próximo acesso. As sessões anteriores serão invalidadas.</p></Editor>}
 {edit?.kind==="enroll"&&rowUser&&<Editor title={`Matrículas de ${rowUser.displayName}`} onClose={()=>setEdit(null)} onSave={f=>save("/admin/enrollments",{userId:rowUser.id,classId:value(f,"classId"),active:true})}><div className="wide">{data.enrollments.filter(e=>e.studentProfileId===rowUser.profileId).map(e=><p key={e.classId}>{data.classes.find(c=>c.id===e.classId)?.name} <Button onClick={()=>action("/admin/enrollments",{userId:rowUser.id,classId:e.classId,active:false})}>Pausar matrícula</Button></p>)}</div><Select label="Adicionar turma" name="classId">{groupOptions}</Select></Editor>}
 {edit?.kind==="question"&&<QuestionEditor key={edit.id??"new-question"} data={data} question={rowQuestion} onClose={()=>setEdit(null)} onSave={body=>save(`/admin/questions${edit.id?`/${edit.id}`:""}`,body,edit.id?"PUT":"POST")}/>}
 {edit?.kind==="theme"&&<ThemeEditor key={edit.id??"new-theme"} data={data} bank={bank} theme={rowTheme} onClose={()=>setEdit(null)} onSave={body=>save(`/admin/themes${edit.id?`/${edit.id}`:""}`,body,edit.id?"PUT":"POST")}/>}
 {edit?.kind==="release"&&rowTheme&&<Editor title={`Liberar ${rowTheme.versions[0]?.title} para turma`} onClose={()=>setEdit(null)} onSave={f=>save(`/admin/themes/${rowTheme.id}/releases`,{classId:value(f,"classId"),active:true,releaseAt:value(f,"releaseAt")?new Date(value(f,"releaseAt")).toISOString():undefined})}><p className="wide">A turma receberá a revisão publicada atual. Alunos matriculados a verão na data de liberação.</p><Select label="Turma" name="classId">{data.classes.filter(c=>c.isActive&&c.languageId===rowTheme.languageId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Input label="Agendar (opcional; vazio libera agora)" name="releaseAt" type="datetime-local" required={false}/><div className="wide">{rowTheme.releases.map(r=><p key={r.classId}>{data.classes.find(c=>c.id===r.classId)?.name}: {r.isActive?"liberado":"pausado"} {r.releaseAt&&new Date(r.releaseAt).toLocaleString("pt-BR")} {r.isActive&&<Button onClick={()=>action(`/admin/themes/${rowTheme.id}/releases`,{classId:r.classId,active:false})}>Suspender</Button>}</p>)}</div></Editor>}
 {tab==="overview"&&<><p>Crie uma turma, matricule alunos e libere um tema publicado. O aluno conclui o nascimento e inicia as missões.</p><div className="admin-stats">{[["Turmas",data.classes.length],["Alunos",data.users.filter(u=>u.role==="Student").length],["Temas",data.themes.length],["Perguntas",bank.length]].map(([label,total])=><section className="admin-stat" key={label}><span>{label}</span><strong>{total}</strong></section>)}</div><h2>Acompanhamento dos alunos</h2><div className="table-wrap admin-card"><table><thead><tr><th>Aluno</th><th>Acesso</th><th>Bloo / XP</th><th>Etapa dos temas</th></tr></thead><tbody>{data.users.filter(u=>u.role==="Student").map(u=><tr key={u.id}><td>{u.displayName}</td><td>{u.lastLoginAt?"Já acessou":"Não acessou"}</td><td>{u.bloos.map(b=>`${b.stage==="Hatchling"?"Nasceu":"Ovo"} · ${b.xp} XP`).join(", ")||"Sem matrícula"}</td><td>{u.progress.map(p=>`${data.themes.find(t=>t.id===p.themeId)?.versions[0]?.title??"Tema"}: ${p.status==="Completed"?"Concluído":p.currentDifficulty}`).join("; ")||"Não iniciou"}</td></tr>)}</tbody></table></div></>}
 {tab==="password"&&<Editor title="Alterar minha senha" onClose={()=>changeTab("overview")} onSave={async f=>{if(value(f,"newPassword")!==value(f,"confirm"))throw new Error("password_confirmation");await api.changePassword(token,value(f,"currentPassword"),value(f,"newPassword"));onLogout();}}><Input label="Senha atual" name="currentPassword" type="password"/><Input label="Nova senha (mínimo 12 caracteres)" name="newPassword" type="password" minLength={12} maxLength={128}/><Input label="Confirmar nova senha" name="confirm" type="password" maxLength={128}/><p className="wide">Após salvar, entre novamente com sua nova senha.</p></Editor>}
 {tab!=="overview"&&tab!=="password"&&<label className="searchbar"><input aria-label="Buscar registros" className="input" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Buscar…"/></label>}
 {(tab==="students"||tab==="admins")&&<><div className="table-wrap admin-card"><table><thead><tr><th>Nome / login</th><th>Estado</th><th>Turmas / senha</th><th>Ações</th></tr></thead><tbody>{paginate(persons).map(p=><tr key={p.id}><td><strong>{p.displayName}</strong><br/>{p.login}</td><td>{p.isActive?"Ativo":"Inativo"}</td><td>{p.mustChangePassword?"Troca de senha pendente":"Senha definida"}<br/>{data.enrollments.filter(e=>e.studentProfileId===p.profileId).map(e=>data.classes.find(c=>c.id===e.classId)?.name).join(", ")}</td><td><div className="row-actions"><Button onClick={()=>open("user",p.id)}>Editar</Button><Button onClick={()=>p.id===user.id?changeTab("password"):open("reset",p.id)}>Alterar senha</Button>{p.role==="Student"&&<Button onClick={()=>open("enroll",p.id)}>Matrículas</Button>}</div></td></tr>)}</tbody></table></div>{pager(persons.length)}</>}
 {tab==="classes"&&<><div className="table-wrap admin-card"><table><thead><tr><th>Turma</th><th>Nível / período</th><th>Alunos</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{paginate(groups).map(c=><tr key={c.id}><td>{c.name}</td><td>{c.levelLabel} · {c.period}</td><td>{data.enrollments.filter(e=>e.classId===c.id).length}</td><td>{c.isActive?"Ativa":"Inativa"}</td><td><Button onClick={()=>open("class",c.id)}>Editar turma</Button></td></tr>)}</tbody></table></div>{pager(groups.length)}</>}
 {tab==="themes"&&<><p>Temas são lidos do banco. Publicar não libera automaticamente para turmas: use “Liberar para turma”.</p><div className="table-wrap admin-card"><table><thead><tr><th>Tema</th><th>Revisão</th><th>Níveis / perguntas</th><th>Turmas liberadas</th><th>Ações</th></tr></thead><tbody>{paginate(themes).map(t=><tr key={t.id}><td><strong>{t.versions[0]?.title}</strong><br/>{t.status==="Active"?"Ativo":"Fechado"}</td><td>v{t.versions[0]?.versionNumber} · {t.versions[0]?.status==="Published"?"Publicada":"Rascunho"}</td><td>{t.versions[0]?.difficulties.join(", ")}<br/>{t.versions[0]?.questionVersionIds.length} perguntas</td><td>{t.releases.filter(r=>r.isActive).map(r=>data.classes.find(c=>c.id===r.classId)?.name).join(", ")||"Nenhuma"}</td><td><div className="row-actions"><Button onClick={()=>open("theme",t.id)}>Ver / nova revisão</Button>{t.currentPublishedVersionId&&<Button onClick={()=>open("release",t.id)}>Liberar para turma</Button>}<Button onClick={()=>action(`/admin/themes/${t.id}/status`,{active:t.status!=="Active"})}>{t.status==="Active"?"Fechar":"Reabrir"}</Button></div></td></tr>)}</tbody></table></div>{pager(themes.length)}</>}
 {tab==="questions"&&<><p>Editar cria uma nova versão: sessões e temas publicados preservam a pergunta anterior.</p><div className="table-wrap admin-card"><table><thead><tr><th>Questão</th><th>Enunciado</th><th>Nível / publicação</th><th>Ações</th></tr></thead><tbody>{paginate(questions).map(q=><tr key={q.id}><td>{q.code}<br/>v{q.versions[0]?.versionNumber}</td><td>{q.versions[0]?.prompt}</td><td>{q.versions[0]?.difficulty}<br/>{!q.isActive?"Arquivada":q.versions[0]?.status==="Published"?"Publicada":"Rascunho"}</td><td><div className="row-actions"><Button onClick={()=>open("question",q.id)}>Ver / editar</Button><Button onClick={()=>action(`/admin/questions/${q.id}/status`,{active:!q.isActive})}>{q.isActive?"Arquivar":"Reativar"}</Button></div></td></tr>)}</tbody></table></div>{pager(questions.length)}</>}
 </>}</div></section></main>;
}
function QuestionEditor({data,question,onSave,onClose}:{data:Workspace;question?:BankQuestion;onSave:(body:unknown)=>Promise<void>;onClose:()=>void}){
 const current=question?.versions[0];
 return <Editor title={question?"Prévia / nova versão da pergunta":"Nova pergunta"} onClose={onClose} onSave={f=>onSave({languageId:value(f,"languageId"),skillId:value(f,"skillId"),difficulty:value(f,"difficulty"),type:value(f,"type"),prompt:value(f,"prompt"),explanation:value(f,"explanation"),options:[0,1,2,3].map(i=>({text:value(f,`option${i}`),isCorrect:value(f,"correct")===String(i)})).filter(o=>o.text.trim()),publish:f.has("publish")})}>
 <Select label="Idioma" name="languageId" initial={question?.languageId}>{data.languages.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select><Select label="Habilidade / categoria" name="skillId" initial={current?.skillId}>{data.skills.map(s=><option key={s.id} value={s.id}>{data.categories.find(c=>c.id===s.skillCategoryId)?.name} · {s.name}</option>)}</Select><Select label="Dificuldade" name="difficulty" initial={current?.difficulty}>{levels.map(l=><option key={l}>{l}</option>)}</Select><Select label="Tipo" name="type" initial={current?.type}><option value="MultipleChoice">Múltipla escolha</option><option value="FillBlankWithOptions">Completar com alternativas</option></Select><label className="field wide">Enunciado<textarea className="input" name="prompt" required maxLength={600} defaultValue={current?.prompt}/></label><label className="field wide">Explicação<textarea className="input" name="explanation" required maxLength={600} defaultValue={current?.explanation}/></label>{[0,1,2,3].map(i=><Input key={i} label={`Alternativa ${String.fromCharCode(65+i)}${i>1?" (opcional)":""}`} name={`option${i}`} initial={current?.options[i]?.text} required={i<2} maxLength={300}/>)}<Select label="Alternativa correta" name="correct" initial={String(current?.options.findIndex(o=>o.isCorrect)??0)}>{[0,1,2,3].map(i=><option key={i} value={i}>{String.fromCharCode(65+i)}</option>)}</Select><label><input type="checkbox" name="publish" defaultChecked={current?.status==="Published"}/> Publicar esta versão</label></Editor>;
}
function ThemeEditor({data,bank,theme,onSave,onClose}:{data:Workspace;bank:BankQuestion[];theme?:Theme;onSave:(body:unknown)=>Promise<void>;onClose:()=>void}){
 const current=theme?.versions[0];const [selected,setSelected]=useState(current?.questionVersionIds??[]),[enabled,setEnabled]=useState(current?.difficulties??levels),[query,setQuery]=useState("");
 const available=bank.filter(q=>q.isActive).flatMap(q=>q.versions.filter(v=>v.status==="Published").map(v=>({...v,code:q.code})));
 return <Editor title={theme?"Prévia / nova revisão do tema":"Novo tema"} onClose={onClose} onSave={f=>onSave({languageId:value(f,"languageId"),title:value(f,"title"),description:value(f,"description"),difficulties:enabled,questionVersionIds:selected,publish:f.has("publish")})}><Input label="Título" name="title" initial={current?.title}/><Select label="Idioma" name="languageId" initial={theme?.languageId}>{data.languages.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select><label className="field wide">Descrição<textarea className="input" name="description" required maxLength={800} defaultValue={current?.description}/></label><div className="wide"><strong>Níveis habilitados</strong><div className="row-actions">{levels.map(l=><label key={l}><input type="checkbox" checked={enabled.includes(l)} onChange={e=>setEnabled(e.target.checked?[...enabled,l]:enabled.filter(d=>d!==l))}/> {l} ({available.filter(q=>q.difficulty===l&&selected.includes(q.id)).length}/5 mínimo)</label>)}</div></div><div className="wide"><label>Selecionar perguntas publicadas<input className="input" placeholder="Buscar enunciado ou código" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="question-picker">{available.filter(q=>`${q.code} ${q.prompt}`.toLowerCase().includes(query.toLowerCase())).map(q=><label key={q.id}><input type="checkbox" checked={selected.includes(q.id)} onChange={e=>setSelected(e.target.checked?[...selected,q.id]:selected.filter(id=>id!==q.id))}/><span>{q.difficulty} · {q.code} · v{q.versionNumber}<br/>{q.prompt}</span></label>)}</div></div><label><input name="publish" type="checkbox" defaultChecked={current?.status==="Published"}/> Publicar revisão</label><p className="wide">Selecione ao menos 5 perguntas por nível. Depois de publicar, use “Liberar para turma”. Revisões já liberadas não são alteradas automaticamente.</p></Editor>;
}
