"use client";

import { Bird, BookOpen, Database, Home, Layers3, LogOut, Plus, UserRound, UsersRound } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api, AuthUser, StudentRecord } from "@/lib/api";

type AdminTab = "overview" | "classes" | "students" | "themes" | "questions";

export default function AdminApp({ token, user, onLogout }: { token: string; user: AuthUser; onLogout: () => void }) {
  const [tab, setTab] = useState<AdminTab>("overview");
  const [students, setStudents] = useState<StudentRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); try { setStudents((await api.listStudents(token)).items); } finally { setLoading(false); } }, [token]);
  useEffect(() => { void refresh(); }, [refresh]);
  const menu: [AdminTab, typeof Home, string][] = [["overview", Home, "Início"], ["classes", Layers3, "Turmas"], ["students", UsersRound, "Alunos"], ["themes", BookOpen, "Temas"], ["questions", Database, "Banco de questões"]];
  return <main className="admin"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Bird size={24} /></span><span>Bird<span className="brand-dot">League</span></span></div><nav className="side-nav">{menu.map(([id, Icon, label]) => <button key={id} className={`side-link ${tab === id ? "active" : ""}`} onClick={() => setTab(id)}><Icon size={19} /><span>{label}</span></button>)}</nav><button className="side-link" style={{ position: "absolute", bottom: 25, left: 18, right: 18 }} onClick={onLogout}><LogOut size={19} /><span>Sair</span></button></aside><section className="admin-content"><header className="admin-head"><div><strong>Bluebird Idiomas</strong><small>Portal administrativo</small></div><span className="pill"><UserRound size={16} /> {user.displayName} · Admin</span></header><div className="admin-main">{tab === "overview" ? <Overview name={user.displayName} students={students} setTab={setTab} /> : tab === "students" ? <Students token={token} students={students} loading={loading} onCreated={refresh} /> : <EmptySection tab={tab} />}</div></section></main>;
}

function Overview({ name, students, setTab }: { name: string; students: StudentRecord[]; setTab: (tab: AdminTab) => void }) {
  const active = students.filter(student => student.isActive).length;
  const accessed = students.filter(student => student.lastLoginAt).length;
  return <><div className="admin-title"><div><h1>Olá, {name}.</h1><p>Acompanhe os acessos reais cadastrados na escola.</p></div><button className="btn btn-blue btn-small" onClick={() => setTab("students")}><Plus size={17} /> Novo aluno</button></div><div className="admin-stats"><div className="admin-stat"><div className="admin-stat-top"><span>Alunos cadastrados</span><UsersRound size={18} /></div><strong>{students.length}</strong><span className="trend">{active} ativos</span></div><div className="admin-stat"><div className="admin-stat-top"><span>Já acessaram</span><UserRound size={18} /></div><strong>{accessed}</strong><span className="trend">Contas com primeiro login</span></div></div><section className="admin-card" style={{ marginTop: 18 }}><div className="admin-card-head"><h2>Alunos recentes</h2><button className="btn btn-ghost btn-small" onClick={() => setTab("students")}>Gerenciar</button></div>{students.length ? <div className="table-wrap"><table><thead><tr><th>Aluno</th><th>Login</th><th>Acesso</th></tr></thead><tbody>{students.slice(0, 5).map(student => <tr key={student.id}><td><strong>{student.fullName}</strong></td><td>{student.login}</td><td><span className={`status ${student.lastLoginAt ? "blue" : "gray"}`}>{student.lastLoginAt ? "Já acessou" : "Ainda não acessou"}</span></td></tr>)}</tbody></table></div> : <div className="empty-state">Nenhum estudante cadastrado. Crie o primeiro acesso para começar.</div>}</section></>;
}

function Students({ token, students, loading, onCreated }: { token: string; students: StudentRecord[]; loading: boolean; onCreated: () => Promise<void> }) {
  const [creating, setCreating] = useState(false); const [fullName, setFullName] = useState(""); const [login, setLogin] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await api.createStudent(token, { fullName, login, password }); setFullName(""); setLogin(""); setPassword(""); setCreating(false); await onCreated(); } catch (reason) { const code = reason instanceof Error ? reason.message : ""; setError(code === "login_already_exists" ? "Esse login já está em uso." : code === "weak_password" ? "Use uma senha de pelo menos 8 caracteres, diferente do login e não comum." : "Não foi possível criar o estudante. Confira os dados."); } finally { setSaving(false); } }
  return <><div className="admin-title"><div><h1>Alunos</h1><p>Somente estudantes cadastrados aqui podem entrar no BirdLeague.</p></div><button className="btn btn-blue btn-small" onClick={() => setCreating(value => !value)}><Plus size={17} /> Novo aluno</button></div>{creating && <form className="admin-card student-form" onSubmit={submit}><div className="field"><label htmlFor="student-name">Nome completo</label><input id="student-name" className="input" value={fullName} onChange={e => setFullName(e.target.value)} required /></div><div className="field"><label htmlFor="student-login">Login</label><input id="student-login" className="input" value={login} onChange={e => setLogin(e.target.value)} pattern="[A-Za-z0-9._-]{3,80}" required /></div><div className="field"><label htmlFor="student-password">Senha inicial</label><input id="student-password" className="input" type="password" minLength={8} maxLength={128} value={password} onChange={e => setPassword(e.target.value)} required /></div>{error && <p role="alert" style={{ color: "var(--red)" }}>{error}</p>}<button className="btn btn-blue btn-small" disabled={saving}>{saving ? "Criando..." : "Criar acesso"}</button></form>}<section className="admin-card"><div className="admin-card-head"><h2>{loading ? "Carregando..." : `${students.length} aluno(s)`}</h2></div>{students.length ? <div className="table-wrap"><table><thead><tr><th>Aluno</th><th>Login</th><th>Estado</th><th>Último acesso</th></tr></thead><tbody>{students.map(student => <tr key={student.id}><td><strong>{student.fullName}</strong></td><td>{student.login}</td><td><span className={`status ${student.isActive ? "" : "gray"}`}>{student.isActive ? "Ativo" : "Inativo"}</span></td><td>{student.lastLoginAt ? new Date(student.lastLoginAt).toLocaleString("pt-BR") : "Ainda não acessou"}</td></tr>)}</tbody></table></div> : !loading && <div className="empty-state">Nenhum estudante cadastrado.</div>}</section></>;
}

function EmptySection({ tab }: { tab: "classes" | "themes" | "questions" }) {
  const config = { classes: ["Turmas", "Organize alunos, idiomas e temas liberados."], themes: ["Temas", "Crie missões, publique revisões e libere para turmas."], questions: ["Banco de questões", "Edite, publique e reutilize questões pedagógicas."] }[tab];
  return <><div className="admin-title"><div><h1>{config[0]}</h1><p>{config[1]}</p></div></div><section className="admin-card"><div className="empty-state">Ainda não há registros cadastrados nesta área.</div></section></>;
}
