"use client";
import Image from "next/image";
import { ArrowRight, Bird, BookOpen, Check, CheckCircle2, Home, LockKeyhole, LogOut, Sparkles, Trophy, X, Zap } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { achievements } from "@/lib/learning-content";
import { AnswerFeedback, api, AuthUser, Difficulty, JourneySession, JourneyState, TrainingResult } from "@/lib/api";
const blooPath="/assets/bloo/",achievementPath="/assets/achievements/";
const achievementIconAliases:Record<string,string>={ROUTINE_STARTER:"theme-explorer",HABIT_BUILDER:"greetings-climber",ROUTINE_MASTER:"greetings-master",CONSISTENCY_EXPERT:"skill-learned",ACTION_SPOTTER:"theme-explorer",ING_CLIMBER:"greetings-climber",ACTION_MASTER:"greetings-master",NOW_EXPERT:"skill-learned"};
type Tab="home"|"learning"|"achievements";
function Tutorial({onDone}:{onDone:()=>void}){const [step,setStep]=useState(0);const items=[["egg-idle.png","Este é seu Egg","Dentro dele existe um Bloo pronto para aprender com você."],["egg-crack-2.png","Cada resposta ensina","Suas respostas ficam salvas, e erros não impedem o nascimento."],["hatchling-celebrate.png","Vocês crescem juntos","A escola libera temas para sua turma e cada nível traz uma nova missão."]];return <main className="celebrate player-bg"><div className="celebrate-content card"><div className="eyebrow">Passo {step+1} de 3</div><Image src={`${blooPath}${items[step][0]}`} alt="Apresentação da jornada" width={600} height={600}/><h1>{items[step][1]}</h1><p>{items[step][2]}</p><button className="btn btn-primary" onClick={()=>step<2?setStep(step+1):onDone()}>{step<2?"Continuar":"Conhecer meu Egg"}<ArrowRight/></button></div></main>}
function Brand(){return <div className="brand"><span className="brand-mark"><Bird size={24}/></span><span>Bird<span className="brand-dot">League</span></span></div>;}
export default function StudentPortal({token,user,onLogout}:{token:string;user:AuthUser;onLogout:()=>void}){
 const [state,setState]=useState<JourneyState|null>(null),[tab,setTab]=useState<Tab>("home"),[session,setSession]=useState<JourneySession|null>(null),[result,setResult]=useState<TrainingResult|null>(null),[error,setError]=useState(""),[tutorial,setTutorial]=useState(false);
 const refresh=useCallback(()=>api.journey(token).then(setState),[token]);
 useEffect(()=>{refresh().catch(()=>setError("Não foi possível carregar sua jornada."));setTutorial(!localStorage.getItem(`birdleague-tutorial:${user.id}`));},[refresh,user.id]);
 async function start(data:{type:"FirstHatch"|"ThemeMission";themeId?:string;difficulty?:Difficulty}){setError("");try{setSession(await api.startTraining(token,data));}catch(e){const code=e instanceof Error?e.message:"";setError(code==="active_enrollment_required"?"Peça ao administrador para matricular você em uma turma ativa.":code==="theme_not_released"?"Este tema ainda não foi liberado para sua turma.":"Não foi possível iniciar o treino.");}}
 async function resume(id:string){setError("");try{setSession(await api.resumeTraining(token,id));}catch{setError("Não foi possível retomar este treino.");}}
 async function complete(id:string){const done=await api.completeTraining(token,id);setSession(null);setResult(done);await refresh();}
 if(session)return <Quiz token={token} session={session} onExit={()=>setSession(null)} onComplete={()=>complete(session.id)}/>;
 if(tutorial)return <Tutorial onDone={()=>{localStorage.setItem(`birdleague-tutorial:${user.id}`,"seen");setTutorial(false);}}/>;
 if(result?.hatched)return <NameBloo xp={result.xp} token={token} onDone={async()=>{setResult(null);await refresh();}}/>;
 if(result)return <main className="celebrate player-bg"><div className="celebrate-content"><Image src={`${blooPath}hatchling-celebrate.png`} alt="Bloo celebrando" width={700} height={700}/><h1>Treino concluído!</h1><p>{result.correct} de {result.total} respostas corretas · <strong>+{result.xp} XP</strong></p>{result.newlyUnlocked.length>0&&<p>Novas conquistas: {result.newlyUnlocked.map(code=>achievements.find(a=>a[0]===code)?.[2]??code).join(", ")}</p>}<button className="btn btn-primary" onClick={()=>setResult(null)}>Continuar <ArrowRight/></button></div></main>;
 if(!state)return <main className="player-bg"><div className="shell" style={{paddingTop:40}}>{error||"Carregando sua jornada…"}</div></main>;
 const hatched=state.bloo.stage==="Hatchling";
 return <main className="student-shell player-bg"><div className="shell"><header className="student-head"><Brand/><div className="row-actions"><span className="pill"><Zap size={16}/> {state.bloo.xp} XP</span><button className="btn btn-ghost btn-small" aria-label="Sair" onClick={onLogout}><LogOut/></button></div></header></div><div className="student-main">{error&&<p className="form-error">{error}</p>}
 {tab==="home"&&state.pending.length>0&&<section className="card mission-card"><div><h3>Treino em andamento</h3><p>Suas respostas foram preservadas.</p></div><button className="btn btn-primary btn-small" onClick={()=>resume(state.pending[0].id)}>Retomar <ArrowRight/></button></section>}
 {tab==="home"&&<><section className="card bloo-home"><div><div className="eyebrow">{hatched?"Companheiro de Inglês":"Sua jornada começa aqui"}</div><h1>{hatched?`Olá, eu sou ${state.bloo.name}!`:`Olá, ${user.displayName}. Seu Egg está esperando.`}</h1><p>{state.classes.length?`Turma: ${state.classes.join(", ")}`:"Você ainda não possui uma matrícula ativa."}</p>{!hatched&&<button className="btn btn-primary" disabled={!state.classes.length} onClick={()=>start({type:"FirstHatch"})}>{state.pending.some(p=>p.type==="FirstHatch")?"Retomar nascimento":"Ensinar meu Bloo"}<ArrowRight/></button>}</div><Image className="bloo-image" src={`${blooPath}${hatched?"hatchling-idle.png":"egg-idle.png"}`} alt={hatched?state.bloo.name:"Ovo do Bloo"} width={800} height={800}/></section>{hatched&&<MissionList state={state} onStart={start}/>}</>}
 {tab==="learning"&&<><h1>Aprendizado</h1>{hatched?<MissionList state={state} onStart={start}/>:<p>Conclua primeiro o nascimento do seu Bloo.</p>}</>}
 {tab==="achievements"&&<><h1>Conquistas</h1><p>{state.achievements.length} de {achievements.length} desbloqueadas</p><div className="achievement-grid">{achievements.map(([code,name,translation,desc])=><article key={code} className={`card achievement ${state.achievements.includes(code)?"":"locked"}`}><Image src={`${achievementPath}${achievementIconAliases[code]??code.toLowerCase().replaceAll("_","-")}.svg`} alt={translation} width={128} height={128}/><div><h3>{name}</h3><p><strong>{translation}</strong><br/>{state.achievements.includes(code)?desc:"Continue treinando para descobrir."}</p></div></article>)}</div></>}
 </div><nav className="student-nav"><button className={`nav-item ${tab==="home"?"active":""}`} onClick={()=>setTab("home")}><Home/>Início</button><button className={`nav-item ${tab==="learning"?"active":""}`} onClick={()=>setTab("learning")}><BookOpen/>Aprendizado</button><button className={`nav-item ${tab==="achievements"?"active":""}`} onClick={()=>setTab("achievements")}><Trophy/>Conquistas</button></nav></main>;
}
function MissionList({state,onStart}:{state:JourneyState;onStart:(d:{type:"ThemeMission";themeId:string;difficulty:Difficulty})=>void}){return <>{state.themes.length===0?<section className="card learning-card" style={{marginTop:20}}><h3>Nenhum tema liberado</h3><p>O administrador precisa liberar um tema publicado para uma de suas turmas.</p></section>:state.themes.map(theme=><section className="card learning-card" style={{marginTop:20}} key={theme.id}><span className="pill"><BookOpen size={16}/> English</span><h2>{theme.title}</h2><p>{theme.description}</p><div className="difficulty-row">{theme.levels.map(level=><button key={level.difficulty} className={`difficulty ${level.status==="Completed"?"done":level.status==="Available"?"available":""}`} disabled={level.status==="Locked"} onClick={()=>onStart({type:"ThemeMission",themeId:theme.id,difficulty:level.difficulty})}>{level.status==="Completed"?<Check size={14}/>:level.status==="Locked"?<LockKeyhole size={14}/>:null}{level.difficulty}<small>{level.sessionsCompleted?`${level.sessionsCompleted} treino(s) · melhor ${level.bestCorrectAnswers}/5`:level.status==="Available"?"Começar":"Bloqueado"}</small></button>)}</div></section>)}</>}
function Quiz({token,session,onExit,onComplete}:{token:string;session:JourneySession;onExit:()=>void;onComplete:()=>Promise<void>}){
 const missing=session.questions.findIndex(q=>!q.feedback),firstOpen=missing<0?session.questions.length-1:missing;const [index,setIndex]=useState(firstOpen),[selected,setSelected]=useState<string|null>(session.questions[firstOpen]?.feedback?.selectedOptionId??null),[feedback,setFeedback]=useState<AnswerFeedback|null>(session.questions[firstOpen]?.feedback??null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const q=session.questions[index];
 async function check(){if(!selected)return;setBusy(true);setError("");try{setFeedback(await api.answerTraining(token,session.id,{questionId:q.id,selectedOptionId:selected}));}catch{setError("Não foi possível salvar a resposta.");}finally{setBusy(false);}}
 async function next(){if(index===session.questions.length-1){setBusy(true);try{await onComplete();}catch{setError("Não foi possível concluir. Tente novamente.");setBusy(false);}}else{const ni=index+1;setIndex(ni);setSelected(session.questions[ni].feedback?.selectedOptionId??null);setFeedback(session.questions[ni].feedback);}}
 return <main className="player-bg"><div className="quiz"><div className="quiz-head"><button className="btn btn-ghost btn-small" onClick={onExit}><X/></button><div className="progress-track"><span style={{width:`${((index+(feedback?1:0))/session.questions.length)*100}%`}}/></div><span>{index+1} de {session.questions.length}</span></div><section className="card quiz-card"><span className="pill">{session.title}{session.difficulty&&` · ${session.difficulty}`}</span><Image className="quiz-bloo" src={`${blooPath}${session.type==="FirstHatch"?index<2?"egg-crack-1.png":index<4?"egg-crack-2.png":"egg-crack-3.png":feedback?.isCorrect?"hatchling-happy.png":"hatchling-idle.png"}`} alt="Bloo treinando" width={400} height={400}/><h1>{q.prompt}</h1><div className="options">{q.options.map((option,i)=>{let status=selected===option.id?"selected":"";if(feedback&&option.id===feedback.correctOptionId)status="correct";if(feedback&&!feedback.isCorrect&&option.id===feedback.selectedOptionId)status="wrong";return <button disabled={!!feedback} className={`option ${status}`} key={option.id} onClick={()=>setSelected(option.id)}><span className="option-key">{String.fromCharCode(65+i)}</span>{option.text}{feedback&&option.id===feedback.correctOptionId&&<CheckCircle2/>}</button>})}</div>{feedback&&<div className={`feedback ${feedback.isCorrect?"good":"try"}`}>{feedback.isCorrect?<CheckCircle2/>:<Sparkles/>}<div><strong>{feedback.isCorrect?"Boa! Você acertou.":"Quase! Vamos aprender."}</strong><br/>{feedback.explanation}</div></div>}{error&&<p className="form-error">{error}</p>}<div className="quiz-action">{feedback?<button className="btn btn-primary" disabled={busy} onClick={next}>{index===session.questions.length-1?"Concluir treino":"Continuar"}<ArrowRight/></button>:<button className="btn btn-blue" disabled={!selected||busy} onClick={check}>{busy?"Salvando…":"Conferir resposta"}</button>}</div></section></div></main>;
}
function NameBloo({xp,token,onDone}:{xp:number;token:string;onDone:()=>Promise<void>}){const [name,setName]=useState("Bloo"),[busy,setBusy]=useState(false);return <main className="celebrate player-bg"><div className="celebrate-content card"><Image src={`${blooPath}hatchling-celebrate.png`} alt="Bloo nasceu" width={600} height={600}/><h1>Seu Bloo nasceu!</h1><p>Você conquistou +{xp} XP. Escolha um nome ou continue com Bloo.</p><input className="input" maxLength={20} value={name} onChange={e=>setName(e.target.value)}/><button className="btn btn-primary" disabled={busy||name.trim().length<2} onClick={async()=>{setBusy(true);await api.nameBloo(token,name.trim());await onDone();}}>Continuar<ArrowRight/></button></div></main>}
